version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - teamtracker-network

 
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - teamtracker-network

volumes:
  redis_data:

networks:
  teamtracker-network:
    driver: bridge