plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: availability-tracker
  instance-state-name: running

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: instance_type
    prefix: type

hostnames:
  - dns-name
  - private-ip-address

compose:
  ansible_host: public_dns_name